### ISSUE TITLE
Vragen over URI standaard, opmerkingen op organisatie

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#130]
1) In welke zin beantwoort de uri https://test.data.vlaanderen.be/doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585 aan het patroon http(s)://{domein}/{type}/{concept}(/{referentie})* ?
Is hoedanigheid hier niet het concept? maw. is het niet de bedoeling dat de uri er zo uitziet: https://test.data.vlaanderen.be/doc/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585  ?

2) curl -H "Accept: application/rdf+xml" https://test.data.vlaanderen.be/doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585  geeft volgend resultaat:

<rdf:RDF xmlns:dc='http://purl.org/dc/terms/' xmlns:foaf='http://xmlns.com/foaf/0.1/' xmlns:ns0='http://data.vlaanderen.be/ns/organisatie#' xmlns:ns1='http://mu.semte.ch/vocabularies/core/' xmlns:org='http://www.w3.org/ns/org#' xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:xsd='http://www.w3.org/2001/XMLSchema#'>
    <rdf:Description rdf:about='http://data.vlaanderen.be/doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585'>
        <dc:issued rdf:datatype='http://www.w3.org/2001/XMLSchema#dateTime'>2018-05-02T16:06:57Z</dc:issued>      
        <foaf:primaryTopic>
            <dc:Agent rdf:about='http://data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585'>
                <rdf:type rdf:resource='http://data.vlaanderen.be/ns/organisatie#Hoedanigheid'></rdf:type>
                <ns1:uuid>5461d9ff-25eb-2cd0-74ce-faa587096585</ns1:uuid>             
                <org:memberOf rdf:resource='http://data.vlaanderen.be/id/organisatie/OVO000038' />           
                <org:role rdf:resource='http://data.vlaanderen.be/id/concept/hoedanigheid/47e7a8fe-ef3f-3eda-a724-ce0b9c323aaf' />               
                <foaf:name>Tindemans Emmelie</foaf:name>               
            </dc:Agent>           
        </foaf:primaryTopic>     
    </rdf:Description> 
</rdf:RDF>

curl -H "Accept: application/rdf+xml" https://test.data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585  geeft geen resultaat

curl -I -H "Accept: application/rdf+xml" https://test.data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585 
HTTP/1.1 303 See Other
Content-Length: 0
Date: Wed, 02 May 2018 16:19:55 GMT
Location: /doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585
Server: Caddy
Vary: Accept
X-Request-Id: b18779bb-58ee-4331-8bdb-4dae13b728ce
X-Response-Time: 0.252ms

curl -L -H "Accept: application/rdf+xml" https://test.data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585 
<html><head><title>502 Bad Gateway</title></head><body><h1>502 Bad Gateway</h1><h2>undefined</h2><p>connect EHOSTUNREACH 10.0.0.36:80</p><p><pre><code>Error: connect EHOSTUNREACH 10.0.0.36:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)</code></pre></p></body></html>

**Comment by gezever** [comment]
Maw. Indien de redirect curl -L -H "Accept: application/rdf+xml" https://test.data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585 zou werken, en dit de standaard aanpak is, kan ik enkel informatie over een object krijgen via het document.
Ik wil info over het object, niet over het document.

**Comment by bertvannuffelen** [comment]
topic 1)
`
In welke zin beantwoort de uri https://test.data.vlaanderen.be/doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585 aan het patroon http(s)://{domein}/{type}/{concept}(/{referentie})* ?
Is hoedanigheid hier niet het concept? maw. is het niet de bedoeling dat de uri er zo uitziet: https://test.data.vlaanderen.be/doc/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585 
`

Een goede opmerking. Dat kijken we na. De opzet zoals we nu gedaan was om een unieke referentie te hebben en dan zou het waarschijnlijk correct als volgt moeten zijn:

https://test.data.vlaanderen.be/doc/hoedanigheid/OVO000038heeft5461d9ff-25eb-2cd0-74ce-faa587096585

**Comment by bertvannuffelen** [comment]
Topic 3) de bad gateway is een configuratie bug. Die wordt opgelost.

**Comment by bertvannuffelen** [comment]
Topic 4) 
Ja dat kan.

**Comment by gezever** [comment]
Beste Bert,
ivm. punt 2 
Ik krijg een antwoord <rdf:RDF><rdf:Description rdf:about='http://data.vlaanderen.be/doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585'> <foaf:primaryTopic><dc:Agent rdf:about='http://data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585'/><foaf:primaryTopic><rdf:Description/></rdf:RDF> 
ipv. 
<rdf:RDF><dc:Agent rdf:about='http://data.vlaanderen.be/id/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585'/></rdf:RDF> 
terwijl ik gewoon info over de id wil.
1.) Is dit complexe antwoord de logische implementatie van de redirect? En dus, gaan wij dat ook zo moeten doen? In dat geval overweeg ik te adviseren om dit aspect van de uri-strategie niet te volgen bij departement omgeving.
2.) <rdf:Description rdf:about='http://data.vlaanderen.be/doc/organisatie/OVO000038/hoedanigheid/5461d9ff-25eb-2cd0-74ce-faa587096585'>  is niet getypeerd. Ik ga ervan uit dat dit object van een type :Document is, maar bij mijn weten is dit model in de Oslo2 standaarden niet ter sprake gekomen.

**Comment by bertvannuffelen** [comment]
Dag,

ivm topic 2. Ik zie je probleem niet. Dit is een RDF document waarin je ook data vind over de identifier en ook over het RDF document. Waarom is voor jou dit een probleem? 
De inhoud van een RDF subject pagina kan vele verschillende definities hebben. Een voorbeeld. De hoedanigheid verwijst naar een rol. Moet de preflabel van die rol mee opgenomen worden of niet, enz.
Dit is een van de vele keuze mogelijkheden.

Een ander voorbeeld is b.v. een dossier dat naar een adresvoorstelling verwijst (wat geen publieke identifier heeft). Steek je dat in de respons?

De enige voorwaarde die een RDF subject pagina heeft is dat het minstens 1 triple heeft met de identifier waarover het gaat als subject. Al de rest is vrij te kiezen.

Enkele voorbeelden waarom deze informatie nuttig kan zijn. Je kan hiermee een caching strategie uitbouwen: namelijk zolang de er minder dan 6u verstreken is t.o.v. de generatietimestamp moet je geen refresh doen. Of je kan dit gebruiken in afgeleide informatie bronnen. Namelijk de afgeleide informatie is gebouwd op data die verkregen is op de generatietimestamp. Tenslotte kan het ook gebruikt worden om data problemen te debuggen. 

Kan je beter verwoorden wat je eigenlijk probleem hiermee is?

Bert

**Comment by bertvannuffelen** [comment]
Ivm typering. Dat heb ik open gelaten. Maar ik weet niet of we dat moeten doen. Maar `document` zou hier een passend type zijn.

**Comment by gezever** [comment]
Ik heb het wat beter nagekeken en het is het wel getypeerd als foaf:Document door het gebruik van foaf:primaryTopic.
Was het niet de bedoeling van Oslo2 om tot afspraken ivm. data-uitwisseling te komen? 
Het subject is nu altijd het foaf:Document. Al de rest wordt in eerste instantie object.

**Comment by gezever** [comment]
Wat de adresvoorstelling in een blank node betreft, niemand zal je kwalijk nemen dat je dit in een subject page van een dossiet steekt.

**Comment by bertvannuffelen** [comment]
Ivm de typering http://data.vlaanderen.be/doc/document: het concept document hier is anders dan de vorm doc (ook document). 

We hebben voor zover ik weet de notie document niet gestandaardiseerd in OSLO. Maar dat neemt niet weg dat /doc ook wel een betekenis heeft: namelijk het document over ... 

Dus in dit geval door 
`<http://data.vlaanderen.be/doc/adres/123> foaf:primaryTopicOf <http://data.vlaanderen.be/id/adres/123>` expliciteer ik de URI strategie definitie dat /doc/{ref} een document is over de /id/{ref}.

Niets meer. Dit is niet in tegenspraak met de URI strategie: dat is de lezing die ik geef aan de de URI strategie. 

Tenzij we ook willen stellen dat alle documenten over een 'echte wereld entiteit' niet een afspiegeling zijn van deze entiteit maar ook dingen zijn die op zichzelf staan. Dus /id/{ref} en /id/document/{ref} voor dezelfde ref onafhankelijk bestaan en hebben een bredere relatie dan id/{ref} en /doc/{ref}. Maar ik denk dat dit niet zal voorvallen. Ik kan me geen voorbeeld voor de geest halen waarbij ik /id/document/{ref} zou willen gebruiken als de identificator voor het document over ref dat breder gaat dan de interpretatie van ref.  

Bij het schrijven van dit antwoord denk ik dat we /doc kunnen interpreteren als de verkorting van /id/document voor identificatoren die een puri hebben /id.

Wat wel een uitdaging is ivm documenten is dat er verschillende menselijk leesbare varianten bestaan en dat deze niet kunnen gedisambigueerd worden puur via content-negotatie.  Er is b.v. de technische leesbare vorm zoals die op data.vlaanderen.be, maar je kan ook een beschrijvende pagina hebben en deze laatste kan technisch zijn (b.v. een medische beschrijving, of een wettekst), maar ook vulgariserend, naar kinderen gericht, enz.  En dat is niet zo triviaal te realiseren.

**Comment by GeertThijs** [comment]
Ter info: De associatie wordtBeschrevenDoor gemapt op primaryTopicOf is intussen afgevoerd. Een klasse Document was er al, we hebben er wel nog Documentonderdeel aan toegevoegd. Zie bijgevoegde figuur.
![image](https://user-images.githubusercontent.com/22620291/42952814-80fd2eaa-8b79-11e8-9b11-035f18f65774.png)
